version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  app-sealgo:
    container_name: app-sealgo
    image: herwindra/app-sealgo
    ports:
      - "8080:8080"
